module.exports = angular.module('lkApp',[
    'ngAnimate',
    'ngCookies',
    'ui.router',
    'ui.router.state.events',
    'pascalprecht.translate',
    'ngSanitize',
    'ngTouch',
    // 'angularMoment',
    'oc.lazyLoad',
    'LocalStorageModule',
    'ui.bootstrap',
    'blockUI',
    'colorpicker.module',
    'toastr',
    'ui.router.tabs',
    'ui.tree',
    'ngVerify',
    'ui.select'
]);